id: ID2F7D1C8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:17:16+00:00'
last_modified: '2022-06-08T05:19:41.196361+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ2398
  title: གུང་ཐང་པའི་ཤེས་རབ་སྙིང་པོའི་སྔགས་ཀྱི་རྣམ་བཤད་དང་ཅོ་ནེ་བླ་མ་བློ་བཟང་རྒྱ་མཚོའི་ལྟ་མགུར་སོགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    46FE:
      image_group_id: I1CZ2452
      title: Volume 1 of gung thang pa'i shes rab snying po'i sngags kyi rnam bshad
        dang co ne bla ma blo bzang rgya'i mtsho'i lta mgur sogs
      total_pages: 242
      order: 1
      base_file: 46FE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
